### PR TITLE
Added the ability to comment on a map

### PR DESCRIPTION
**Pull request by YosoraLife**
It only a small change, but i think more people could benefit from this.

I am using Waymark to display motorcycle routes on my websites. And i thought it would be nice if people could comment/discuss those routes. So since Waymaps is a custom post type, I added the default wordpress ability to comment on a map.

### CODE REVIEW

**Comment by morehawes** [comment]
Hi @YosoraLife,

Thank you for submitting this, I actually think allowing comments for Maps makes complete sense and would make a nice addition to the plugin :)

My only concern with this change is that by enabling this capability by default, some users with existing Maps might not realise and may unknowingly start publishing Maps with comments enabled by default (depending on the `Discussion Settings > Default post settings > Allow people to submit comments on new posts` WordPress Setting).

Adding a Waymark Setting to enable/disable comments would be one way around this.

Do you have any thoughts?

Cheers,

Joe

**Comment by YosoraLife** [comment]
Hi Joe,

I understand where you're coming from. And I agree that code changes should not affect already published maps. But this would only affect new cards. And then again, for newly published maps, this would only affect those who have enabled commenting on their site.

I have a bit of mixed feelings about an extra setting. On the one hand, you have already built in many settings (which I have also gratefully made use of) and there will undoubtedly be people who want comments on their posts but not comments on the maps (although they can also disable comments per map). 

On the other hand, it is an extra setting that ultimately needs to be maintained. And it's just a small adjustment, but every little bit adds up. It would be a shame if it all became so much that the plugin could no longer be maintained.

Cheers,
Remco

**Comment by morehawes** [comment]
Hi @YosoraLife,

> Would it also be an idea to add 'excerpt' to the supports array?

I am not apposed to this, but I am a little weary of overwhelming the Map Create/Edit interface by enabling too many of the Post capabilities.

I think instead of a PR this might be better broken up into a separate Issue for further discussion.

I am traveling at the moment and will give these some more time when I return.

Thanks again!

Joe

**Comment by YosoraLife** [comment]
>I think instead of a PR this might be better broken up into a separate Issue for further discussion.

No problem, i'll open a separate issue. Enjoy your travels ;)

**Comment by morehawes** [comment]
Hi @YosoraLife,

I have released version 1.2.0 of the plugin which includes the ability to enable comment support.

Please do let me know if you encounter any issues!

Thanks again for the suggestion.

Joe

**Pull request closed without merging**
